import { InterweavedKnot } from './interweaved-knot';
import { Point, lineIntersection } from './tying-logic';

export type MandrelMetrics = {
  strandWidth: number;
  gapWidth: number;
  cellSize: number;
  margin: number;
  pinRadius: number;
  outlineWidth: number;
};

export type MandrelPin = Point & {
  strandIndex: number;
  pinNumber: number; // 0-indexed within that strand's bight sequence
};

export type MandrelLine = {
  from: MandrelPin;
  to: MandrelPin;
  strandIndex: number;
  isBackslash: boolean;
  isFreeRun: boolean;
};

export type MandrelCrossing = {
  x: number;
  y: number;
  backslashLine: MandrelLine;
  slashLine: MandrelLine;
  isBackslashOver: boolean;
};

export function makeMandrelMetrics(strandWidth: number, gapWidth: number): MandrelMetrics {
  const cellSize = strandWidth + gapWidth;
  return {
    strandWidth,
    gapWidth,
    cellSize,
    margin: cellSize * 2,
    pinRadius: gapWidth / 2,
    outlineWidth: 2,
  };
}

export function getPinPositions(
  knot: InterweavedKnot,
  m: MandrelMetrics
): { left: MandrelPin[]; right: MandrelPin[] } {
  const totalPins = knot.numStrands * knot.bights;
  const mandrelWidth = (knot.parts - 1) * m.cellSize;
  const isOddParts = knot.parts % 2 !== 0;

  const left: MandrelPin[] = [];
  const right: MandrelPin[] = [];

  for (let p = 0; p < totalPins; p++) {
    const strandIndex = p % knot.numStrands;
    const pinNumber = Math.floor(p / knot.numStrands);
    const y = m.margin + p * m.cellSize + m.cellSize / 2;

    left.push({ x: m.margin, y, strandIndex, pinNumber });
    right.push({
      x: m.margin + mandrelWidth,
      y: isOddParts ? y - m.cellSize / 2 : y,
      strandIndex,
      pinNumber,
    });
  }

  return { left, right };
}

export function getHalfCycleLines(
  knot: InterweavedKnot,
  m: MandrelMetrics
): MandrelLine[] {
  const { left, right } = getPinPositions(knot, m);
  const lines: MandrelLine[] = [];

  knot.strands.forEach((strand, strandIndex) => {
    const leftPins = left.filter(p => p.strandIndex === strandIndex);
    const rightPins = right.filter(p => p.strandIndex === strandIndex);

    // pin arrays are 0-indexed by pinNumber; halfCycle.fromPin/toPin are 1-indexed bight numbers
    // fromPin/toPin are 1-indexed bight numbers generated by Knot.fillPins() — always in [1, bights]
    // The ?? fallback is a safety net that should never trigger for valid knot data
    const leftPin = (n: number): MandrelPin => leftPins[n - 1] ?? leftPins[0];
    const rightPin = (n: number): MandrelPin => rightPins[n - 1] ?? rightPins[0];

    strand.halfCycles.forEach((hc, hcIndex) => {
      const goingRight = hcIndex % 2 === 0; // HC 0 starts left, goes right
      const from = goingRight ? leftPin(hc.fromPin) : rightPin(hc.fromPin);
      const to = goingRight ? rightPin(hc.toPin) : leftPin(hc.toPin);
      const isFreeRun = hc.runs.length === 0;

      lines.push({
        from,
        to,
        strandIndex,
        isBackslash: to.y > from.y,
        isFreeRun,
      });
    });
  });

  return lines;
}

export function getCrossings(
  lines: MandrelLine[],
  knot: InterweavedKnot,
  m: MandrelMetrics
): MandrelCrossing[] {
  const mandrelWidth = (knot.parts - 1) * m.cellSize;
  const crossings: MandrelCrossing[] = [];

  const backslashLines = lines.filter(l => l.isBackslash && !l.isFreeRun);
  const slashLines = lines.filter(l => !l.isBackslash && !l.isFreeRun);

  for (const bl of backslashLines) {
    for (const sl of slashLines) {
      const pt = lineIntersection(bl.from, bl.to, sl.from, sl.to);
      if (!pt) continue;

      // Exclude crossings at or outside mandrel edges
      if (pt.x <= m.margin + 1 || pt.x >= m.margin + mandrelWidth - 1) continue;

      // Determine over/under from strand coding at crossing column
      const col = Math.floor((pt.x - m.margin) / m.cellSize);
      const strand = knot.strands[bl.strandIndex];
      if (col < 0 || col >= strand.coding.length) continue;

      const isBackslashOver = (strand.coding[col] === '\\') !== strand.sobre;

      crossings.push({
        x: pt.x,
        y: pt.y,
        backslashLine: bl,
        slashLine: sl,
        isBackslashOver,
      });
    }
  }

  return crossings;
}
